ResetFailures()
ExpectEq("?", GetSystemInfo(10).name, "Unexplored")
SetFleetDestination(1, 10)
EndTurn()
ExpectEq(0, GetExplorationEventCount(), "turn 1")
EndTurn()
ExpectEq(0, GetExplorationEventCount(), "turn 2")
EndTurn()
ExpectEq(0, GetExplorationEventCount(), "turn 3")
EndTurn()
ExpectEq(1, GetExplorationEventCount(), "arrival")
ExpectEq(10, GetExplorationEvent(1))
ExpectEq("Leo Minor", GetSystemInfo(10).name, "Explored")
EndTurn()
ExpectEq(0, GetExplorationEventCount(), "idle")